# site settings
title: Harshad Bhandwaldar
subtitle:
email: hbhandwaldar@gmail.com
description: "Growing up in the west-central regions of India, I developed a keen interest in the evolution of computer science, especially with the advancements in technology. This passion led me to pursue a graduate degree in Computer Science at Binghamton University in New York State. Throughout my academic journey, I focused on expanding my expertise through key courses such as Cloud Computing, Operating Systems, Design and Analysis of Algorithms, High-Performance Computing, and Computer Organization and Architecture."
baseurl: "/home" # the subpath of your site, e.g. /blog
url: "https://hb0313.github.io/"
author: Harshad Bhandwaldar
street_address: Atlanta
city: Atlanta
state: GA
zip_code: 13905
country: United States of America
phone: (999) 999-9999

# homepage tiles
tiles-source: pages # accepts "posts" or "pages"
tiles-count: 4

# social settings (key must match name of font awesome icon)
# see https://fontawesome.com/icons?d=gallery&p=2&s=brands
# Icons are not shown if value is empty
# You need to restart jekyll for changes to have an effect
socials:
  GitHub: https://github.com/hb0313
  LinkedIn: https://www.linkedin.com/in/harshadbhandwaldar/
  Twitter: https://twitter.com/harshadb1303

# build settings
markdown: kramdown

sass:
  style: compressed

exclude:
- "*.gemspec"
- LICENSE.md
- CONTRIBUTING.md
- README.md
